# Site settings
title: "No ACK Expected: Musings of a Software Engineer"
name: "Michael Cibulskis"
email: "Michael.Cibulskis@noackexpected.com"
description: > # this means to ignore newlines until "baseurl:"
  Contemplation of matters pertaining to software development,
  consulting, and learning.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://noackexpected.com" # the base hostname & protocol for your site
twitter_username: mcibulskis
github_username:  mcibulskis

# Build settings
markdown: kramdown
